services:

  catalog-service:
    depends_on:
      - polar-postgres
    image: "catalog-service"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
      - "8001:8001"
    networks:
      - catalog-network

    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001

  config-service:
    image: config-service
    container_name: config-service
    ports:
      - 8888:8888
    networks:
      - catalog-network


  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - "5432:5432"

    networks:
      - catalog-network
    environment:
      - POSTGRES_USER=hoonseung
      - POSTGRES_PASSWORD=4617
      - POSTGRES_DB=polardb_catalog


networks:
  catalog-network:
